<div class="alert alert-danger">
    <h4>Achtung Beta-Version</h4>
    <p>
        Bei der vorliegenden Webseite handelt es sich um eine Beta-Version des neuen Discovery-Auftritts der Württembergischen Landesbibliothek.
        <br> Aktuell kann es daher noch vereinzelt zu Darstellungsfehlern oder irritierenden Suchergebnissen kommen. Dafür bitten wir Sie um Ihr Verständnis.
        <br> Die bisherige Discovery-Seite erreichen Sie weiterhin unter der Adresse <a href="wlb2.boss.bsz-bw.de">wlb2.boss.bsz-bw.de</a>.
    </p>
    <p>
        Sollten Sie auf ein Problem in der Seite oder den Suchergebnissen stoßen, melden Sie diesen gerne per Mail an <a href="mailto:boss-support@bsz-bw.de">boss-support@bsz-bw.de</a>. Vielen Dank!
    </p>
</div>
