<div class="alert alert-danger">
    <h4>Achtung Beta-Version</h4>
    Es handelt sich um eine Beta-Version des neuen Katalog Plus der WLB. Aktuell kann es noch zu Darstellungsproblemen kommen.
    Sollten Sie auf Fehler stoßen, melden Sie diese gerne per Mail an <a href="mailto:katalogplus@wlb-stuttgart.de">katalogplus@wlb-stuttgart.de</a>. Vielen Dank!
</div>
<p></p>
<p>
    Suchen Sie im Katalog Plus der Württembergischen Landesbibliothek nach Büchern, Zeitschriften, Aufsätzen, Karten, Noten und anderen Medien folgender Bestände und Sammlungen:
    <ul>
        <li>Württembergische Landesbibliothek</li>
        <li>Internationale Hölderlin-Bibliographie</li>
        <li>Stefan George-Bibliographie</li>
        <li>Deutsche Pharmazeutische Zentralbibliothek</li>
        <li>wissenschaftliche Bibliotheken aus den Verbundregionen von GBV und SWB (K10 Plus)</li>
        <li>frei zugängliche Online-Publikationen (Open Access)</li>
        <li>wissenschaftliche Aufsätze aus zahlreichen Datenbanken</li>
    </ul>
    Wenn Sie nur nach Beständen der Württembergischen Landesbibliothek suchen möchten, grenzen Sie in der Erweiterten Suche auf „WLB-Bestand“ ein, oder nutzen Sie bei Ihren Suchergebnissen den Filter „WLB-Bestand“.
    Für die gezielte Recherche in der Landesbibliographie Baden-Württemberg und den Bibliographien der Literaturarchive von Stefan George und Friedrich Hölderlin können Sie ebenfalls die entsprechende Eingrenzung in der Erweiterten Suche oder die Filter bei Ihren Suchergebnissen nutzen.
    Über den Reiter „Fernleihe“ können Medien und einzelne Aufsätze bestellt werden, die nicht im Bestand der WLB sind.
</p>