Ihre Fernleihbestellung ist bei uns eingegangen, vielen Dank.

Bestellnummer: <?=$this->orderId?>

Titel: <?=$this->orderTitle?>


Sobald die bestellten Medien eingetroffen sind, werden wir Sie benachrichtigen.

Gewünschter Abholort: <?=$this->orderPlace?>


Sie haben Fragen?
Dann schreiben Sie uns:
- Abholort Campus Mainz und BB Universitätsmedizin: passivefl@ub.uni-mainz.de
- Abholort BB TSK, Campus Germersheim: bbtsk-benutzung@ub.uni-mainz.de

Viele Grüße
Ihre Universitätsbibliothek