<p>Die Frankreich-Bibliothek des Deutsch-Französischen Instituts (dfi) ist eine sozialwissenschaftliche Spezialbibliothek mit umfangreichen Beständen zu den Themenbereichen</p>
<ul>
    <li>Politik, Wirtschaft, Gesellschaft und kulturelles Leben in Frankreich seit 1944</li>
    <li>Geschichte und Gegenwart der deutsch-französischen Beziehungen</li>
    <li>Frankreich und Deutschland im europäischen und internationalen Kontext</li>
    <li>französische Außenbeziehungen</li>
    <li>deutsch-französische und internationale Vergleiche</li>
</ul>
<p>Monographien, Zeitschriften- und Buchbeiträge, graue Literatur und wissenschaftliche Volltexte finden Sie unter <a href="/">Bibliotheksbestand</a>, Presse- und Interartikel unter <a href="Search2/">Presseartikel</a>.</p>