<p>The Frankreich-Bibliothek is a special library with extensive holdings on the subject areas</p>
<ul>
    <li>Politics, economy, society and cultural life in France since 1944</li>
    <li>Franco-German relations, historical and contemporary</li>
    <li>France and Germany in the European and international context</li>
    <li>French foreign relations</li>
    <li>Franco-German and international comparisons</li>
</ul>