<p>La Frankreich-Bibliothek de l’institut franco-allemand (dfi) est une bibliothèque spécialisée dans la littérature en sciences sociales disposant d’un très vaste fonds sur les domaines suivants:</p>
<ul>
    <li>vie politique, économique, sociale et culturelle en France</li>
    <li>histoire et actualité des relations franco-allemandes</li>
    <li>la France et l'Allemagne en Europe et dans le monde</li>
    <li>relations étrangères françaises</li>
    <li>comparaisons franco-allemandes et internationales</li>
</ul>