sudo: false
language: php
php:
  - 5.6
  - 7.0
  - 7.1

env:
  - VUFIND_HOME=$PWD VUFIND_LOCAL_DIR=$PWD/local

before_script:
  - phpenv config-rm xdebug.ini
  - phpenv rehash
  - composer install
  - npm install -g eslint@"<3.0.0"
  - mkdir $VUFIND_LOCAL_DIR/reports/
  - mkdir $VUFIND_LOCAL_DIR/reports/coverage

cache:
  directories:
    - downloads
    - $HOME/.composer/cache

script:
  - vendor/bin/phing phpunit-local phpcs-console php-cs-fixer-dryrun eslint

after_script:
  - vendor/bin/phing codacy-local
