<h2>Rechercheportal der UB Mainz</h2>
<ul>
    <li>
        <strong>Bibliothekskatalog</strong> Bestand der Universitätsbibliothek Mainz (Bücher, Zeitschriften, Online-Ressourcen und andere Medien)
    </li>
    <li>
        <p><strong>Mehr Literatur</strong> Online zugängliche Aufsätze und Bücher, Literaturhinweise aus verschiedenen Datenbanken. Hier wird Ihnen auch Literatur angezeigt, die sich nicht im Bestand der Universitätsbibliothek Mainz befindet.</p>
    </li>
    <li>
        <p><strong>Fernleihe</strong> Bestand des Gemeinsamen Verbünde Index (GVI), der die bibliographischen Daten aller deutschen Verbundkataloge enthält.<br>
            Mit der Fernleihe haben Sie die Möglichkeit, vor Ort nicht vorhandene Literatur im Original oder als (Aufsatz-)Kopie deutschlandweit aus anderen Bibliotheken zu bestellen. Ausführliche Informationen zur Fernleihe finden Sie <a href="https://www.ub.uni-mainz.de/de/faq#fernleihe" target="_blank">hier</a>.
        </p>
    </li>
</ul>
<p>Beachten Sie bitte, dass nicht alle für die Johannes Gutenberg-Universität verfügbaren Datenbanken durchsucht werden! Für eine detaillierte sachliche Suche empfehlen wir, direkt in einer <a href="https://dbis.ur.de/UBMZ/browse/subjects/" class="external" target="_blank">Fachdatenbank</a> zu recherchieren.</p>
