<ul>
    <li>
        <strong>Bibliothekskatalog</strong> Bestand der Universitätsbibliothek Mainz (Bücher, Zeitschriften, Online-Ressourcen und andere Medien)
    </li>
    <li>
        <p><strong>Mehr Literatur</strong> Online zugängliche Aufsätze und Bücher, Literaturhinweise aus verschiedenen Datenbanken. Hier wird Ihnen auch Literatur angezeigt, die sich nicht im Bestand der Universitätsbibliothek Mainz befindet.</p>
        <p>Beachten Sie bitte, dass nicht alle für die Johannes Gutenberg-Universität verfügbaren Datenbanken durchsucht werden! Für eine detaillierte sachliche Suche empfehlen wir, direkt in einer <a href="https://dbis.ur.de/UBMZ/browse/subjects/" class="external" target="_blank">Fachdatenbank</a> zu recherchieren.</p>
    </li>
</ul>
