<ul>
    <li>
        <strong>Library catalog</strong> Mainz University Library’s holdings (books, journals, online resources, etc.)
    </li>
    <li>
        <p><strong>More literature</strong> Articles and books available online, search results from bibliographic databases, etc. Search results include material which is not part of Mainz University Library’s holdings.</p>
        <p>Please note that some databases available at Johannes Gutenberg University are not included here. For a detailed search in a specific field of study, we recommend using one of the  <a href="https://dbis.ur.de/UBMZ/browse/subjects/" class="external" target="_blank">subject specific databases</a> zu recherchieren.</p>
    </li>
</ul>
<div>
    <p>&nbsp</p>
</div>