<h2>Mainz University Library Search Portal</h2>
<ul>
    <li>
        <strong>Library catalog</strong> Mainz University Library’s holdings (books, journals, online resources, etc.)
    </li>
    <li>
        <p><strong>More literature</strong> Articles and books available online, search results from bibliographic databases, etc. Search results include material which is not part of Mainz University Library’s holdings.</p>
    </li>
    <li>
        <p><strong>Interlibrary Loan</strong> The Combined Consortial Library Index (GVI, Gemeinsamer Verbünde Index) comprises the bibliographic data of all German library networks. <br>
            Through the interlibrary loan service, you can request materials from libraries across Germany that are not available locally, either as originals or as copies of journal articles. Detailed information about interlibrary loan is available <a href="https://www.ub.uni-mainz.de/en/faq#interlibrary-loan" target="_blank">here</a>.
        </p>
    </li>
</ul>
<p>Please note that some databases available at Johannes Gutenberg University are not included here. For a detailed search in a specific field of study, we recommend using one of the  <a href="https://dbis.ur.de/UBMZ/browse/subjects/" class="external" target="_blank">subject specific databases</a>.</p>
