<p>
    Dies ist eine Teststellung zur Anbindung des Open-Source Discoverysystems <a href="https://wiki.bsz-bw.de/display/BOSS">BOSS</a> an <a href="https://wiki.bsz-bw.de/display/BWFOLIO">FOLIO</a>. BOSS basiert auf <a href="https://vufind.org">VuFind®</a>.
</p>
<p>
    Konkret geht es hier um den Fernleih-Workflow mit BOSS und ReShare/Folio unter Anbindung des Zentralen Fernleihservers des BSZ.
</p>
<p>
    Bei technischen Fragen und Anregungen: <a href="javascript:window.location.href = 'mailto:' + ['boss-support','bsz-bw.de'].join('@')">boss-support@bsz-bw.de</a><br/><br/>
</p>


