<p>
    This is a test application for connecting the open source discovery system <a href="https://wiki.bsz-bw.de/display/BOSS">BOSS</a> to <a href="https://wiki.bsz-bw.de/display/BWFOLIO">FOLIO</a>. BOSS is based on <a href="https://vufind.org">VuFind®</a>.
</p>

<p>
    Specifically, here the interlibrary loan workflow is tested, using BOSS and ReShare/Folio, integrated with the BSZ's central interlibrary loan server.
</p>

<p>
    For technical questions and suggestions: <a href="javascript:window.location.href = 'mailto:' + ['boss-support','bsz-bw.de'].join('@')">boss-support@bsz-bw.de</a><br/><br/>
</p>