<?php foreach ($checkboxFilters as $current): ?>
    <div class="facet verticalcenter" >
        <?php $hidden = (!($results->getResultTotal() > 0 || $current['selected'] || $current['alwaysVisible'])) ?>
        <a class="checkbox-filter<?php if($hidden): ?> hidden<?php endif; ?>" href="<?=$current['selected'] ? $results->getUrlQuery()->removeFilter($current['filter']) : $results->getUrlQuery()->addFilter($current['filter']);?>" data-facet="<?=$this->escapeHtmlAttr($current['filter'])?>" data-facet="<?=$this->escapeHtmlAttr($current['filter'])?>">
            <?php if ($current['selected']): ?>
                <span class="sr-only"><?=$this->transEsc('clear_tag_filter') ?></span>
            <?php endif; ?>
            <span class="text">
        <i class="fa fa-<?=$current['selected'] ? 'check-square-o' : 'square-o' ?>"></i>
                <?=$this->transEsc($current['desc']) ?>
      </span>
            <?php if (!$current['selected']): ?>
                <span class="badge avail-count"></span>
            <?php endif; ?>
        </a>
        <?php if ($this->client()->is($current['desc']) && !$hidden): ?>
            <?php $imgLink = $this->imageLink('/logo/bibliographies/' . $current['desc'] .".png" ); ?>
            <span class="vertcenter"><img class="lineicon" src="<?=$imgLink?>" alt="<?=$current['desc']?>"></span>
        <?php endif ?>
        <?php if ($this->client()->is('wlb_facet_tooltip')): ?>
            <a class="external hasicon" href="https://www.wlb-stuttgart.de/die-wlb/wir-ueber-uns/abteilungen/pflichtexemplare/"><span class="" data-toggle="tooltip" title="<?=$this->transEsc('ePflicht-BW Tooltip')?>"><i class="fa fa-info-circle text-success"></i></span></a>
        <?php endif ?>
    </div>
<?php endforeach; ?>
