<?php
    $ignoreHiddenFilterMemory = $this->ignoreHiddenFilterMemory ?? false;
    $ignoreHiddenFiltersInRequest = $this->ignoreHiddenFiltersInRequest ?? false;
    $hiddenFilters = $this->searchTabs()->getHiddenFilters($this->searchClassId, $ignoreHiddenFilterMemory, $ignoreHiddenFiltersInRequest);
    if (empty($hiddenFilters) && !$ignoreHiddenFilterMemory) {
        $hiddenFilters = $this->searchMemory()->getLastHiddenFilters($this->searchClassId);
        if (empty($hiddenFilters)) {
            $hiddenFilters = $this->searchTabs()->getHiddenFilters($this->searchClassId);
        }
    }
    $hiddenFilterParams = $this->searchTabs()->getCurrentHiddenFilterParams($this->searchClassId, $ignoreHiddenFilterMemory, '?'); ?>
<?php if (count($searchTabs) > 0): ?>
    <ul class="nav nav-tabs" role="menu">
        <?php foreach ($searchTabs as $tab): ?>
            <?php if ($this->permission()->allowDisplay($tab['permission'])): ?>
                <li<?= $tab['selected'] ? ' class="active"' : '' ?>
                        id="<?= $this->transEsc(strtolower($tab['id'])) ?>"
                        role="none presentation">
                    <a <?= $tab['selected'] ? '' : 'href="' . $this->escapeHtmlAttr($tab['url']) . '"' ?>>
                        <i class="fa <?= $this->escapeHtmlAttr($tab['icon']) ?>"></i>
                        <span class="text"><?= $this->transEsc($tab['label']); ?></span></a>
                </li>
            <?php elseif ($block = $this->permission()->getAlternateContent($tab['permission'])): ?>
                <?= $block ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php if ($this->client()->is('advanced_search_in_tabs')):?>
            <li class="">
                <a class="text-link" href="<?=$this->url('search-advanced') . ((isset($this->searchId) && $this->searchId) ? '?edit=' . $this->escapeHtmlAttr($this->searchId) : $hiddenFilterParams)?>" >
                    <span class="text"><?= $this->transEsc("Advanced Search") ?></span>
                    <i class="fa fa-chevron-right"></i>
                </a>
            </li>
        <?php endif; ?>
    </ul>
<?php endif; ?>
