  <?php $account = $this->auth()->getManager(); ?>

  <?php /*  Logo: only for reichenau on left side
  <?php if ($this->client()->is('show_header_logo')): ?>
      <a href="<?=$this->client()->getWebsite('')?>" >
          <?php $logoFile = $this->clientAsset()->getLogo(); ?>
          <img src="<?= $this->imageLink($logoFile) ?>" class="img-responsive" style="height:3em" alt="Logo Bibliothek">
      </a>
  <?php endif; ?>
*/ ?>

<div class="banner container">
          <?php /*  Burgermenu */ ?>
          <?php if (!isset($frame)): ?>
          <div class="navbar-header">
              <button type="button" class="navbar-toggle btn btn-primary"
                      data-toggle="collapse" data-target="#header-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <i class="fa fa-bars"></i>
              </button>
          </div>
          <?php endif; ?>

          <?php /*  Expanded menu */ ?>
          <?php if (!isset($this->layout()->renderingError)): ?>
              <div class="collapse navbar-collapse" id="header-collapse">
                      <ul class="nav navbar-nav navbar-right flip">
                          <?php if ($this->feedback()->tabEnabled()): ?>
                              <li>
                                  <a class="icon-link" id="feedbackLink" data-lightbox href="<?=$this->url('feedback-home') ?>">
                                      <?=$this->icon('feedback', 'icon-link__icon') ?>
                                      <span class="icon-link__label"><?=$this->transEsc('Feedback')?></span>
                                  </a>
                              </li>
                          <?php endif; ?>
                          <?php $cart = $this->cart(); ?>
                          <?php if ($cart->isActive()): ?>
                              <li id="cartSummary" aria-live="polite" aria-atomic="true">
                                  <a id="cartItems" class="icon-link" data-lightbox title="<?=$this->transEscAttr('View Book Bag')?>" href="<?=$this->url('cart-home')?>">
                                      <?=$this->icon('cart', 'icon-link__icon') ?>
                                      <span class="icon-link__label">
                  <span class="sr-only"><?=$this->transEsc('Book Bag')?>:</span>
                  <span role="status"><strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?></span>
                  <span class="full<?=!$cart->isFull() ? ' hidden' : '' ?>">(<?=$this->transEsc('bookbag_full') ?>)</span>
                </span>
                                  </a>
                              </li>
                          <?php endif; ?>
                          <?php if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
                              <?php if ($account->getIdentity()): ?>
                                  <li class="logoutOptions<?php if ($account->dropdownEnabled()): ?> with-dropdown<?php endif ?>">
                                      <a href="<?=$this->url('myresearch-home', [], ['query' => ['redirect' => 0]])?>" class="icon-link">
                                          <span id="account-icon" class="icon-link__icon"><?=$this->icon('my-account') ?></span>
                                          <span class="icon-link__label"><?=$this->transEsc('Your Account')?></span>
                                      </a>
                                  </li>
                                  <?php if ($account->dropdownEnabled()): ?>
                                      <li id="login-dropdown" class="dropdown hidden-xs">
                                          <a href="#" data-toggle="dropdown"><?=$this->icon('dropdown-caret') ?></a>
                                          <div class="dropdown-menu">
                                              <?=$this->accountMenu()->render('', 'header_')?>
                                          </div>
                                      </li>
                                  <?php endif; ?>
                                  <li class="logoutOptions">
                                      <a href="<?=$this->url('myresearch-logout')?>" class="logout icon-link">
                                          <?=$this->icon('sign-out', 'icon-link__icon') ?>
                                          <span class="icon-link__label"><?=$this->transEsc('Log Out')?></span>
                                      </a>
                                  </li>
                              <?php else: ?>
                                  <li id="loginOptions">
                                      <?php if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                                          <a href="<?=$this->url('myresearch-userlogin')?>" class="icon-link">
                                              <?=$this->icon('sign-in', 'icon-link__icon') ?>
                                              <span class="icon-link__label"><?=$this->transEsc('Institutional Login')?></span>
                                          </a>
                                      <?php else: ?>
                                          <a href="<?=$this->url('myresearch-userlogin')?>" class="icon-link" data-lightbox>
                                              <?=$this->icon('sign-in', 'icon-link__icon') ?>
                                              <span class="icon-link__label"><?=$this->transEsc('Login')?></span>
                                          </a>
                                      <?php endif; ?>
                                  </li>
                              <?php endif; ?>
                          <?php endif; ?>
                          <?php if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
                              <?=$this->component('menu-button', [
                                  'toggleLabel' => 'Theme',
                                  'wrapperClass' => 'theme-selector',
                                  'wrapperTag' => 'li',
                                  'menuItems' => array_map(
                                      function ($item) {
                                          $item['label'] = $item['desc'];
                                          $item['url'] = $this->url()->addQueryParameters(['ui' => $item['name']]);

                                          return $item;
                                      },
                                      $this->layout()->themeOptions
                                  ),
                              ]) ?>
                          <?php endif; ?>
                          <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
                              <li class="language dropdown">
                                  <form method="post" name="langForm" id="langForm">
                                      <input type="hidden" name="mylang"/>
                                  </form>
                                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img
                                              src="<?= $this->imageLink('flags/' . $this->layout()->userLang . '.png') ?>"
                                              alt="Language Flag"/> <i class="fa fa-caret-down"></i></a>
                                  <ul class="dropdown-menu">
                                      <?php foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                                          <li <?= $this->layout()->userLang == $langCode ? ' class="active"' : '' ?>>
                                              <a class="" href="#"
                                                 onClick="document.langForm.mylang.value='<?= $langCode ?>';document.langForm.submit()">
                                                  <img src="<?= $this->imageLink('flags/' . $langCode . '.png') ?>"
                                                       alt="Flag <?= $this->displayLanguageOption($langName) ?>"/>
                                                  <?= $this->displayLanguageOption($langName) ?>
                                              </a>
                                          </li>
                                      <?php endforeach; ?>
                                  </ul>
                              </li>
                          <?php endif; ?>
                          <li class="home">
                              <a class="lang-<?= $this->layout()->userLang ?> ellipsis" href="<?= $this->url('home') ?>"><i
                                          class="fa fa-home"></i><span class="sr-only"><?= $this->transEsc('Home') ?></span>
                                  <?php if ($this->client()->isIsilSession() && $this->client()->hasIsilSession()): ?>
                                      <?php $library = $this->libraries()->getFirstActive($this->client()->getIsils()) ?>
                                      <?= $this->escapeHtml((string)$library) ?>
                                  <?php elseif ($this->client()->isIsilSession() && !$this->client()->hasIsilSession()): ?>
                                      <?= $this->transEsc('ILL::button_choose_library') ?>
                                  <?php endif; ?>
                              </a>
                          </li>
                      </ul>
              </div>
          <?php endif; ?>
</div>

  <?php /* SearchTabs, input-field, virtual keyboard, field types, submit-button, links  */ ?>
<div class="container">
  <?php if ($this->client()->is('show_searchbox_logo')): ?>
  <div class="row">
      <div class="sidebar col-sm-4 col-md-3 hidden-print">
          <?= $this->clientAsset()->getLogoHtml() ?>
      </div>
      <?php if ($this->layout()->searchbox !== false): ?>
          <div class="col-sm-8 col-md-9">
              <?= $this->layout()->searchbox ?>
          </div>
      <?php endif; ?>
  </div>
  <?php elseif ($this->layout()->searchbox !== false): ?>
      <?= $this->layout()->searchbox ?>
  <?php endif; ?>
</div>
  <?php /* BSZ wozu?
<?php if ($this->layout()->searchbox !== false && !$this->client()->is('disable_searchbar')): ?>
  <div class="search container navbar">
    <div class="nav searchbox hidden-print" role="search">
      <?=$this->layout()->searchbox ?>
    </div>
  </div>
<?php endif; ?>
*/ ?>
