<?php foreach ($this->driver->getFormats() as $format): ?>
    <?php if ($format == 'Online' || $format == 'E-Book'): ?>
        <?php $labelclass = "label-success"?>
    <?php else: ?>
        <?php $labelclass="label-info"?>
    <?php endif ?>
    <span class="label <?=$labelclass?> <?= $this->record($this->driver)->getFormatClass($format) ?>"><?= $this->transEsc('Formats::'.$format) ?></span>
<?php endforeach; ?>
<?php if ($this->driver->tryMethod('isEPflicht')):?>
        <span class="label label-warning" data-toggle="tooltip" title="<?=$this->transEsc('ePflicht-BW Text')?>"><?=$this->transEsc('ePflicht-BW Label')?></span>
<?php endif ?>
