<h2>Willkommen im Bibliothekskatalog ‌</h2>
<p>
    Suchen Sie im Bibliothekskatalog nach Büchern, Zeitschriften, E-Ressourcen, Abschlussarbeiten und anderen Medien im Bestand der Bibliothek der TH Bingen.
</p>
<p>
    Über „Weitere Medien“ finden Sie frei zugängliche Online-Publikationen (Open Access) und Aufsätze.
</p>

<p>
    Bei technischen Fragen und Anregungen: <a href="javascript:window.location.href = 'mailto:' + ['boss-support','bsz-bw.de'].join('@')">boss-support@bsz-bw.de</a><br/><br/>
</p>
