<h2>Welcome to the library catalogue</h2>
<p>
    Search the library catalog for books, journals, e-resources, theses and other media in the TH Bingen library collection.
</p>
<p>
    You can find freely accessible online publications (open access) and articles under “Other Media”.
</p>
<p>
    For technical questions and suggestions: <a href="javascript:window.location.href = 'mailto:' + ['boss-support','bsz-bw.de'].join('@')">boss-support@bsz-bw.de</a><br/><br/>
</p>