# https://de.wikipedia.org/wiki/YAML

# If there are multiple fields configured, all of them must match.
# Order is important for performance, most common entries should be listed first.
# Values are regex patterns (wildcard is "."), multiple values can be separated by ", ".
# More specific formats should be inserted before broad ones.

# catch Online videos with repeated 007, this must be listed before book
Video:
  - field: Leader
    position: 6
    value: g
  - field: "007"
    value: cr
  - field: "007"
    value: vu
Video2:
  - field: "500"
    subfield: a
    value: "Streaming video"
Audio2:
  - field: "500"
    subfield: a
    value: "Streaming audio"
# text
Book:
  - field: Leader
    position: 6
    value: a, m # a = print, m=online
  - field: Leader
    position: 7
    # i is originally integrated ressources but we consider this as books
    value: m, i
  - field: "007"
    value: t., cr, cz
# serials
Journal:
  - field: Leader
    position: 7
    value: s
  - field: "008"
    position: 21
    value: p
Newspaper:
  - field: Leader
    position: 7
    value: s
  - field: "008"
    position: 21
    value: n
MonographSeries:
  - field: Leader
    position: 7
    value: s
  - field: "008"
    position: 21
    value: m
Serial:
  - field: Leader
    position: 7
    value: s
MusicalScore:
  - field: Leader
    position: 6
    value: c
# would be more correct but is missing in many records
#  - field: "007"
#    value: q.
Map:
  - field: Leader
    position: 6
    value: e, f
  - field: "007"
    value: a.
Globe:
  - field: Leader
    position: 6
    value: e
  - field: "007"
    value: d.
SoundRecording:
  - field: Leader
    position: 6
    value: j, i
  - field: "007"
    value: so, su
MusicRecording_Cassette:
  - field: Leader
    position: 6
    value: j
  - field: "007"
    value: ss
MusicRecording_Platter:
  - field: Leader
    position: 6
    value: j
  - field: "007"
    value: sz
MusicRecording_Disc:
  - field: Leader
    position: 6
    value: j
  - field: "007"
    value: sd
MusicRecording:
  - field: Leader
    position: 6
    value: j
  - field: "007"
    value: s.
# video, motion picture
VideoCartridge:
  - field: Leader
    position: 6
    value: g
  - field: "007"
    value: vc
Video_Disc:
  - field: Leader
    position: 6
    value: g
  - field: "007"
    value: vc, vd
Video_Reel:
  - field: Leader
    position: 6
    value: g
  - field: "007"
    value: vr, mr
    #mr ergänzt
FilmstripCartridge:
  - field: Leader
    position: 6
    value: g
  - field: "007"
    value: gc
Filmslip:
  - field: "007"
    value: gd
Filmstrip:
  - field: Leader
    position: 6
    value: g
  - field: "007"
    value: gf
    #neu aufgenommen, bitte prüfen
Video_Cassette:
  - field: "007"
    value: mf, vf
MotionPicture:
  - field: Leader
    position: 6
    value: g
  - field: "007"
    value: m.
TapeCartridge:
  - field: Leader
    position: 6
    value: m
  - field: "007"
    value: ca, cf
ChipCartridge:
  - field: Leader
    position: 6
    value: m
  - field: "007"
    value: cb
OpticalDisc_DVD-ROM:
  - field: Leader
    position: 6
    value: a, m, g
  - field: "007"
    value: cd, co
  - field: "300"
    subfield: a
    value: ".? DVD-ROM"
OpticalDisc2:
  - field: Leader
    position: 6
    value: m, a
  - field: "007"
    value: cd
DiscCartridge:
  - field: Leader
    position: 6
    value: m
  - field: "007"
    value: cc
TapeReel:
  - field: Leader
    position: 6
    value: m
  - field: "007"
    value: ch
FloppyDisk:
  - field: "007"
    value: cj
MagnetoOpticalDisc:
  - field: "007"
    value: cm
E-JournalOnDisc:
  - field: Leader
    position: 6
    value: m
  - field: "007"
    value: cz
    # possible mis-use of z
OpticalDisc:
  - field: Leader
    position: 6
    value: m, a
  - field: "007"
    value: co
# other
LooseLeaf:
  - field: Leader
    position: 6
    value: a
  - field: "007"
    value: td
Slide:
  - field: Leader
    position: 6
    value: g
  - field: "007"
    value: gs, g.
Microfilm:
  - field: Leader
    position: 6
    value: a
  - field: "007"
    value: h.
VisualMedia:
  - field: Leader
    position: 6
    value: k
  - field: "007"
    value: k., zz
Kit:
  - field: Leader
    position: 6
    value: o
  - field: "007"
    value: o.
Object:
  - field: Leader
    position: 6
    value: r
  - field: "007"
    value: z.
Manuscript:
  - field: Leader
    position: 6
    value: t
Article:
  - field: Leader
    position: 7
    value: a, b
  - field: "007"
    value: t., cr
SensorImage:
  - field: Leader
    position: 6
    value: r
  - field: "007"
    value: r.
Braille:
  - field: Leader
    position: 6
    value: a
  - field: "007"
    value: f.




