<h1>Search and find in the OPAC of TH Bingen</h1>
<p>
    This is a testapplication for connecting the discovery system <a href="https://wiki.bsz-bw.de/display/BOSS">BOSS</a> to <a href="https://wiki.bsz-bw.de/display/BWFOLIO">FOLIO</a>.
</p>
<p>
    BOSS is based on <a href="https://vufind.org">VuFind®</a>.
</p>
<p>
    ...
</p>
<p>
    For technical questions and suggestions: <a href="javascript:window.location.href = 'mailto:' + ['boss-support','bsz-bw.de'].join('@')">boss-support@bsz-bw.de</a><br/><br/>
</p>