<?php $this->headTitle($this->translate('Accessibility')); ?>

<h1><?=$this->transEsc('Accessibility') ?></h1>

<div class="helptext">

    <h2 tabindex = "0">Erklärung zur Barrierefreiheit</h2>
    <main class = "accessibility">
        Diese Erklärung zur Barrierefreiheit gilt für die unter <a href="https://ubmz.hds.hebis.de/">https://ubmz.hds.hebis.de/</a> veröffentlichte Website des Bibliotheksservice-Zentrums Baden-Württemberg (BSZ).<br/>
        <br/>
        Das BSZ ist bemüht, seine Website im Einklang mit folgenden Normen und Standards barrierefrei zugänglich zu machen:<br/>
        <ul>
            <li>
                <a  href   = "https://eur-lex.europa.eu/legal-content/DE/TXT/HTML/?uri=CELEX:32016L2102&from=DE"
                    target = "_blank">
                    Richtlinie&nbsp;(EU)&nbsp;2016/2102 des Europäischen Parlaments und des Rates vom 26.&nbsp;Oktober 2016 über den barrierefreien Zugang zu den Websites und mobilen Anwendungen öffentlicher Stellen
                </a>
            </li>
            <li>
                <a  href   = "https://www.rv.hessenrecht.hessen.de/bshe/document/VB-HE-AD-GVBl2019-18-246"
                    target = "_blank">
                    Hessische Verordnung über barrierefreie Informationstechnik&nbsp;(HVBIT) vom 16.&nbsp;September 2019
                </a>
            </li>
            <li>
                <a  href   = "https://www.gesetze-im-internet.de/bitv_2_0/BJNR184300011.html"
                    target = "_blank">
                    Verordnung zur Schaffung barrierefreier Informationstechnik nach dem Behindertengleichstellungsgesetz (Barrierefreie-Informationstechnik-Verordnung - BITV&nbsp;2.0)
                </a>
            </li>
            <li>
                <a  href   = "https://www.rv.hessenrecht.hessen.de/bshe/document/jlr-BGGHErahmen"
                    target = "_blank">
                    Hessisches Gesetz zur Gleichstellung von Menschen mit Behinderungen (Hessisches Behinderten-Gleichstellungsgesetz&nbsp;-&nbsp;HessBGG) vom 20.&nbsp;Dezember 2004)
                </a>.
            </li>
        </ul>

        <h2 tabindex = "0">Stand der Vereinbarkeit mit den Anforderungen</h2>
        Im Sinne der oben genannten Normen und Standards gilt das Webangebot als eingeschränkt zugänglich.<br/>
        <br/>
        Die Überprüfung der Einhaltung der Anforderungen beruht auf einer am&nbsp;01.09.2021 durchgeführten Selbstbewertung mit Unterstützung durch Dritte.<br/>
        <br/>
        Folgende Einschränkungen in der Barrierefreiheit liegen vor:<br/>
        <ul>
            <li>Fehlende Alternativtexte bei Grafiken und Symbolen</li>
            <li>Links können unverständlich sein.</li>
            <li>Einige Tabellen sind nicht korrekt ausgezeichnet oder werden zur Positionierung von Inhalten eingesetzt.</li>
            <li>Interaktive Elemente (Dialogfenster und Formularelemente) sind nicht barrierefrei bedienbar.</li>
            <li>Einschränkungen der Tastaturbedienbarkeit und des Tastaturfokus</li>
            <li>Auf der Startseite werden keine Informationen in Deutscher Gebärdensprache und Leichter Sprache bereitgestellt.</li>
        </ul>

        <h3 tabindex = "0">Begründung</h3>
        Die Website <a href = "https://ubmz.boss.bsz-bw.de">https://ubmz.boss.bsz-bw.de</a> basiert im Wesentlichen auf der Open-Source-Software VuFind, die nicht barrierefrei vorliegt; die Entwicklung des Angebots hat ihren Ursprung bereits&nbsp;2017. Die Einhaltung der Anforderungen zur barrierefreien Gestaltung würden derzeit eine unverhältnismäßige Belastung darstellen.

        <h3 tabindex = "0">Maßnahmen</h3>
        Der Webauftritt wird an die Anforderungen zur Umsetzung des barrierefreien Internets öffentlicher Stellen angepasst und optimiert. Mit der Übernahme einer in Aussicht gestellten barrierearmen Version der genutzten Open-Source-Software VuFind sowie der sukzessiven Abarbeitung identifizierter und dokumentierter Defizite und Mängel befindet sich das Angebot in einem kontinuierlichen Verbesserungsprozess.<br/>
        <br/>
        Einschränkungen, die sich durch fehlende Kontraste ergeben, können durch die Funktion von Windows&nbsp;10 „Hoher Kontrast“ (Einstellungen, Hoher Kontrast, bspw. Design Kontrast Weiß) behoben werden.<br/>
        <br/>
        Die Seite ist bereits nach WCAG&nbsp;2.1 mit einem responsiven Webdesign voll Reflow-kompatibel und lässt sich auf mobilen Endgeräten mit jeder Orientierung betrachten.

        <h2 tabindex = "0">Datum der Erstellung der Erklärung</h2>
        Diese Erklärung wurde erstellt am&nbsp;01.09.2021.

        <h2 tabindex = "0">Barrieren melden</h2>
        Sie möchten uns bestehende Barrieren mitteilen oder Informationen zur Umsetzung der Barrierefreiheit erfragen? Für Ihr Feedback sowie alle weiteren Informationen erreichen Sie unsere verantwortlichen Kontaktpersonen per E-Mail unter: <a href = "mailto:p2_fragen@dlist.uni-frankfurt.de>">p2_fragen@dlist.uni-frankfurt.de</a><br/>
        <br/>
        Wir sind darum bemüht, Ihre Anfragen innerhalb von sechs Wochen zu beantworten. Sollte eine Antwort unterbleiben oder für Sie nicht zufriedenstellend sein, können Sie sich an die Durchsetzungs- und Überwachungsstelle Barrierefreie Informationstechnik beim Regierungspräsidium in Gießen wenden.<br/>
        <br/>
        Für das <strong>Durchsetzungsverfahren</strong> ist zuständig:<br/>
        <br/>
        Landesbeauftragte für barrierefreie&nbsp;IT<br/>
        Prof.&nbsp;Dr. Erdmuthe Meyer&nbsp;zu&nbsp;Bexten<br/>
        <a  href   = "https://lbit.hessen.de/"
            target = "_blank">
            Link zum Web-Auftritt
        </a>
    </main>

</div>

