<?php $this->headTitle($this->translate('Imprint')); ?>

<h1><?=$this->transEsc('Imprint') ?></h1>

<div class="helptext">

    <h2 tabindex="0">Impressum</h2>
    <main class="imprint">
        <span style="font-style: italic;">Angaben gemäß § 5 DDG</span>
        <br>
        <br>
        Goethe-Universität
        <br>
        <b>hebis-Verbundzentrale</b>
        <br>
        Goethe-Universität Frankfurt | House of Labour
        <br>
        Eschersheimer Landstraße 155 - 157
        <br>
        60323 Frankfurt am Main
        <br>
        <br>
        Telefon: 069 798 39 333
        <br>
        E-Mail: <a href='mailto:p2_fragen@dlist.uni-frankfurt.de'>p2_fragen@dlist.uni-frankfurt.de</a>
        <br>
        <br>
        Umsatzsteuer-Identifikationsnummer (USt-IdNr.): DE 114 110 511
        <br>
        <br>
        Die hebis Verbundzentrale ist organisatorisch Teil der Universitätsbibliothek Johann-Christian-Senckenberg Frankfurt
        am Main. Sie wird gesetzlich vertreten durch den Präsidenten der Goethe-Universität, Prof. Dr. Enrico Schleiff
        <br>
        (<a href='https://www.uni-frankfurt.de/impressum' target='_blank'>Impressum der Goethe-Universität</a>)
        <br>
        <h2 tabindex='0'>Haftungsausschluss</h2>
        <h3 tabindex='0'>Inhalte</h3>
        Die Inhalte unserer Seiten wurden mit größter Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität
        der Inhalte können wir jedoch keine Gewähr übernehmen. Als Diensteanbieter sind wir für eigene Inhalte auf diesen
        Seiten nach den allgemeinen Gesetzen verantwortlich. Wir sind als Diensteanbieter jedoch nicht verpflichtet,
        übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine
        rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den
        allgemeinen Gesetzen bleiben hiervon unberührt.
        <br>
        Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich.
        Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.
        <br>
        <h3 tabindex='0'>Verweise und Links</h3>
        Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können
        wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der
        jeweilige Anbieter oder Betreiber verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf
        mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar.
        <br>
        Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer
        Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend
        entfernen.
    </main>

</div>
