<?php $this->headTitle($this->translate('Privacy')); ?>

<h1><?=$this->transEsc('Privacy') ?></h1>

<div class="helptext">

<h2 tabindex="0">Datenschutzerklärung BSZ - One Stop Search (BOSS)</h2>

<p>
    Diese Datenschutzerklärung dient zur Erfüllung der nach Artikel 13 EU DSGVO geforderten Informationspflicht bei
    Erhebung von Daten zum Zeitpunkt der Erhebung bei betroffenen Personen.
</p>

<h2 tabindex="0">Name und Anschrift des Verantwortlichen</h2>
<p style="padding-left: 30px">
    Johannes Gutenberg-Universität Mainz<br>
    Saarstr. 21<br>
    55122 Mainz<br>
    <br>
    Telefon: 06131 39-0<br>
    Internet: <a href="https://www.uni-mainz.de/">https://www.uni-mainz.de/</a><br>
</p>

<h3>Ausführende Stelle</h3>
<p style="padding-left: 30px">
    Universitätsbibliothek Mainz<br>
    Jakob-Welder-Weg 6<br>
    55128 Mainz<br>
</p>

<h2 tabindex="0">Kontaktdaten der Datenschutzbeauftragten</h2>
<p style="padding-left: 30px">
    Johannes Gutenberg-Universität Mainz<br>
    Der Datenschutzbeauftragte<br>
    Nils Hammerle<br>
    Forum universitatis 2<br>
    55122 Mainz<br>
    <br>
    Telefon: 06131 39-20065<br>
    Telefax: 06131 39-52202<br>
    E-Mail: <a href="mailto:datenschutz@uni-mainz.de">datenschutz@uni-mainz.de</a><br>
    Website: <a href="https://organisation.uni-mainz.de/datenschutzbeauftragter/">
        https://organisation.uni-mainz.de/datenschutzbeauftragter/
    </a><br>
</p>

<p>
    Bei Anfragen oder Beschwerden zum Datenschutz können Sie sich mit dem Datenschutzbeauftragten der Johannes
    Gutenberg-Universität Mainz in Verbindung setzen.
</p>

    <h2 tabindex="0">Name und Anschrift des Auftragsverarbeiters</h2>
    Auftragsverarbeiter ist das Bibliotheksservice-Zentrum Baden-Württemberg (BSZ).<br><br>
<p style="padding-left: 30px">
    <strong>Bibliotheksservice-Zentrum Baden-Württemberg</strong><br>
    Universität Konstanz <br>
    78457 Konstanz<br>
    <br>
    E-Mail: <a href="mailto:datenschutzbeauftragter@bsz-bw.de">datenschutzbeauftragter@bsz-bw.de</a><br>
</p>

<h2 tabindex="0">Rechte und Beschwerdemöglichkeiten</h2>
<p>
    Sie haben das Recht sich bei datenschutzrechtlichen Problemen bei der zuständigen Fachaufsichtsbehörde zu beschweren.
</p>

<h3>Kontaktadresse der Fachaufsichtsbehörde der Johannes Gutenberg-Universität Mainz:</h3>
<p style="padding-left: 30px">
    Der Hessische Beauftragte für Datenschutz und Informationsfreiheit<br>
    Postfach 3163<br>
    65021 Wiesbaden<br>
    <br>
    Telefon: 0611 1408 – 0<br>
    Internet: <a href="https://datenschutz.hessen.de/">https://datenschutz.hessen.de/</a><br>
    Beschwerdeformular: <a href="https://datenschutz.hessen.de/service/beschwerde-uebermitteln">
        https://datenschutz.hessen.de/service/beschwerde-uebermitteln
    </a><br>
</p>
<p>
    Sie haben gegenüber der Johannes Gutenberg-Universität Mainz folgende Rechte hinsichtlich Ihrer gespeicherten
    personenbezogenen Daten:
</p>
<ul>
    <li>Recht auf Auskunft,</li>
    <li>Recht auf Berichtigung oder Löschung,</li>
    <li>Recht auf Einschränkung der Verarbeitung,</li>
    <li>Recht auf Widerruf Ihrer Einwilligung,</li>
    <li>Recht auf Widerspruch gegen die Verarbeitung,</li>
    <li>Recht auf Datenübertragbarkeit, in einer gängigen, strukturierten und maschinenlesbaren Form</li>
</ul>
<p>
    Zur Geltungsmachung dieser Rechte wenden Sie sich an die Mitarbeiter*innen der Johannes Gutenberg-Universität Mainz
    über die E-Mailadresse <a href="mailto:datenschutz@uni-mainz.de">datenschutz@uni-mainz.de</a>
</p>

<h2 tabindex="0">Art der gespeicherten Daten, Zweck und Rechtsgrundlagen, Dauer der Verarbeitung und Löschungsfristen</h2>
<h3>Umgang mit personenbezogenen Daten</h3>
<p>
    Personenbezogene Daten sind Informationen, mit deren Hilfe eine natürliche Person bestimmbar ist, also Angaben, durch
    die Personen identifizierbar sind. Dazu gehören insbesondere Namen, E-Mail-Adressen, Matrikelnummern oder
    Telefonnummern.
</p>
<p>
    Personenbezogene Daten werden von uns nur dann erhoben, genutzt und weitergegeben, wenn dies gesetzlich erlaubt ist
    oder die Nutzer*innen in die Datenerhebung eingewilligt haben. Prinzipiell werden nur die Daten erhoben, die für die
    Nutzung des Dienstes (HDS) notwendig sind. Das sind:
</p>
<p style="padding-left: 30px">
    Name und Vorname<br>
    Adresse und E-Mail-Adresse<br>
    Ausgeliehene / bestellte / vorgemerkte Medien<br>
    Benutzernummer<br>
    Bibliotheksnummer<br>
    Nutzergruppe<br>
    Heimatbibliothek<br>
    Merkliste<br>
    Gespeicherte Suchanfragen<br>
    IP<br>
</p>
<p>
    Sobald der Zweck der Speicherung entfällt, werden die Daten gelöscht.
</p>
<p>
    Rechtsgrundlage für die Verarbeitung personenbezogener Daten ist die Einwilligung der betroffenen Personen gemäß Art.
    6 Abs. 1 Uabs. 1 lit. e) DSGVO i.V.m. § 3 LDSG.
</p>
<p>
    Die Datenerhebung für Bibliothekszwecke erfolgt auf Basis der Benutzungsregelungen der Johannes Gutenberg-Universität.
</p>

<h3>Zugriffsdaten/Server-Logdateien</h3>
<p>
    Beim Zugriff auf die Seiten dieses Webservers werden im Allgemeinen folgende Daten in den Server-Logfiles gespeichert
</p>
<ol>
    <li>IP-Adresse</li>
    <li>Datum und Uhrzeit</li>
    <li>Typ des Client Browsers</li>
    <li>URL der aufgerufenen Seite</li>
    <li>Gegebenenfalls die Fehlermeldung zum aufgetretenen Fehler</li>
    <li>Gegebenenfalls der anfragende Provider</li>
</ol>
<p>
    Diese Daten dienen ausschließlich zum Zwecke der Kontrolle der Funktionalität, der Sicherheit und Fehlerbehebung.
    Diese Nutzung basiert auf EU DSGVO Art. 6 Abs. 1 Uabs. 1 lit. e) DSGVO i.V.m. § 3 LDSG. Alle Logdateien werden
    automatisiert nach spätestens 14 Tagen gelöscht oder anonymisiert. Eine darüberhinausgehende Speicherung ist möglich.
    In diesem Fall werden die IP-Adressen der Nutzer gelöscht oder verfremdet, sodass eine Zuordnung des aufrufenden
    Nutzers nicht mehr möglich ist.
</p>

<h3>Kontaktaufnahme</h3>
<p>
    Zur Kontaktaufnahme mit Mitgliedern der hebis Verbundzentrale (zum Beispiel per Kontaktformular oder E-Mail) werden
    Ihre Angaben zwecks Bearbeitung der Anfrage sowie für den Fall, dass Anschlussfragen entstehen, gespeichert. Nach
    Bearbeitung Ihres Anliegens bzw. nach Erfüllung der Rechtspflicht oder des genutzten Dienstes werden die Daten
    gelöscht, es sei denn, die Aufbewahrung der Daten ist zur Umsetzung berechtigter Interessen der Johannes
    Gutenberg-Universität Mainz oder auf Grund einer gesetzlichen Vorschrift (z.B. Gesetz, Rechtsverordnung, Satzung der
    Johannes Gutenberg-Universität Mainz etc.) erforderlich.
</p>

<h3>Zugriffsgeschützte Webseiten und benutzerbasierte Dienste</h3>
<p>
    Neben den oben genannten Daten werden zusätzlich zur Berechtigungskontrolle des Datenzugriffs der Benutzername oder
    eine Kennung erhoben. Diese Daten werden spätestens nach 14 Tagen gelöscht oder anonymisiert, es sei denn, die
    Aufbewahrung der Daten ist zur Umsetzung berechtigter Interessen der Johannes Gutenberg-Universität oder auf Grund
    einer gesetzlichen Vorschrift (z.B. Gesetz, Rechtsverordnung, Satzung der Johannes Gutenberg-Universität etc.)
    erforderlich.
</p>
<p>
    Für alle Dienste, die nicht unter diese Vorgaben fallen, werden explizit Einwilligungserklärungen eingeholt. Die
    Löschung erfolgt hier je nach Vorgabe des genutzten Dienstes. Die Löschungsfrist wird im Rahmen des Verzeichnisses zur
    Verarbeitungstätigkeiten eindeutig definiert. Die Rechtsgrundlage ist hier EU DSGVO Artikel 6 Absatz 1a).
</p>

<h3 style="display: inline-block;">Shibboleth</h3> (Single-Sign-On)<br>
Beim Shibboleth-Single-Sign-On Verfahren geschehen bei einer Nutzeranmeldung bei einem Anbieter (Service-Provider,
geschützte Anwendung) in der Regel drei Dinge:
<ol>
    <li>
        Ein*e Nutzer*in authentifiziert sich: Durch Eingabe von Nutzername und Passwort beim Shibboleth-Identity-Provider
        (IdP) wird festgestellt, ob die sich anmeldende Person dem System bekannt ist. Der geschützten Anwendung (dem
        Service-Provider, Anbieter) wird dabei unter anderem mitgeteilt, dass sich die Person erfolgreich authentifiziert
        hat.
    </li>
    <li>
        Der Service Provider (SP) kann festlegen, ob der IdP noch weitere Informationen zu der Person bereitstellen muss.
        Die hebis IdPs können Informationen zu UserID, ILN, Heimatsbibliothek, und hebis-spezifischen Gruppenzugehörigkeit
        des/der Nutzer*in liefern.
    </li>
    <li>
        Ein SP kann diese Information propagieren und berechtigten weiteren Diensten mitteilen. Somit kann eine einmalige
        Authentifizierung für mehrere Dienste genutzt werde.
    </li>
    <li>
        All diese Informationen sind für eine bestimmte Zeitspanne gültig. Die Gültigkeit endet jedoch spätestens dann, wenn
        der Browser (die Session) geschlossen wird oder die nutzende Person sich explizit ausloggt.
    </li>
</ol>
<strong>
    Bitte schließen Sie daher an öffentlich zugänglichen Rechnern den Webbrowser, um sich vom Single-Sign-On abzumelden
    und so den Missbrauch Ihres Kontos zu verhindern!
</strong>

<h3>Einbindung von Diensten Dritter</h3>
<p>
    Innerhalb einiger Seiten dieses Onlineangebotes werden Inhalte Dritter, (wie z.B. Redi-Link-Resolver,
    Volltextdatenbanken etc.) von anderen Webseiten eingebunden. Dies setzt immer voraus, dass die Anbieter dieser Inhalte
    (nachfolgend bezeichnet als "Dritt-Anbieter") Ihre IP-Adresse wahrnehmen. Denn ohne diese IP-Adresse könnten die
    Dritt-Anbieter die Inhalte nicht an Ihren Browser senden. Die IP-Adresse ist damit für die Darstellung dieser Inhalte
    erforderlich. Wir bemühen uns, nur solche Inhalte zu verwenden, deren jeweilige Anbieter die IP-Adresse lediglich zur
    Auslieferung der Inhalte verwenden. Jedoch haben wir auf eine weitere Verwendung Ihrer Daten keinen Einfluss (z.B.
    falls die Dritt-Anbieter die IP-Adresse für statistische Zwecke speichern).
</p>

<h3>Analysedienste</h3>
<p>
    Unsere Website verwendet ausschließlich technisch notwendige Cookies. Zu diesem Zweck werden Nutzungsinformationen
    (einschließlich Ihrer gekürzten IP-Adresse) an unseren Server übertragen und zu Nutzungsanalysezwecken gespeichert.
    Diese dienen ausschließlich der Webseitenoptimierung und werden nicht zu Marketingzwecken erhoben. Ihre IP-Adresse
    wird bei diesem Vorgang umgehend anonymisiert, so dass Ihre Nutzung weiterhin anonym erfolgt. Da das Hosting von
    Matomo ausschließlich auf unseren eigenen Servern erfolgt, werden die erzeugten Informationen über Ihre Benutzung
    dieser Webseite nicht an Dritte weitergegeben.
</p>
<p>
    Die Datenverarbeitung erfolgt aufgrund unseres berechtigten Interesses gemäß Art. 6 Abs. 1 Uabs. 1 lit. e) DSGVO
    i.V.m. § 3 LDSG.
</p>
<p>
    Wenn Sie mit der Speicherung und Auswertung dieser Daten nicht einverstanden sind, dann können Sie der Speicherung und
    Nutzung nachfolgend per Mausklick jederzeit widersprechen. In diesem Fall wird in Ihrem Browser ein sog.
    Opt-Out-Cookie abgelegt, was zur Folge hat, dass durch Matomo keine Daten mehr erhoben werden.
</p>
<script defer src = "/themes/hebisbs3/js/privacy-protection-consent-checkbox.js" ></script>
<div id="privacy-protection-klaro">
    <input type="checkbox" id="privacy-protection-checkbox" data-klaro="" onchange="updateConsentWithCheckbox()">
    <label for="privacy-protection-checkbox">
        <div id="privacy-protection-opt-out" class="hidden">
            Statistik nicht erfassen
        </div>
        <div id="privacy-protection-opt-in" class="hidden">
            Statistik erfassen
        </div>
    </label>
</div>

</div>