<h2><?=$this->transEsc('Electronic')?></h2>
<?php foreach ($this->holdings as $holding): ?>
    <?php $label = $this->transEsc($this->client()->getUrlLabel($holding)); ?>
    <?php
    $additional = '';
    if ($holding['signature'] ?? null) {
        $additional = $holding['signature'];
    }
    if ($holding['comment'] ?? null) {
        if ($additional) $additional .= ' &ndash; ';
        $additional .= $holding['comment'];
    }
    ?>
    <?php if (empty($holding['urls']) ): ?>
        <?= $additional ?>
    <?php endif; ?>
    <?php foreach ($holding['urls'] as $url): ?>
        <?php if ($additional): ?>
            <?= $additional ?> &ndash;
        <?php endif; ?>
        <?php if ($this->client()->is('show_url_prefix') && ($holding['prefix'] ?? null)): ?>
            <?= $holding['prefix']?> &ndash;
        <?php endif; ?>
        <a class="external" href="<?=$url['url']?>" target="_blank"><?=$this->transEsc($url['label'])?></a>
        <br>
    <?php endforeach; ?>
<?php endforeach; ?>