<?php
$this->headTitle($this->translate('BibTip') . ': ' . $this->driver->getBreadcrumb());
$content = $this->tab->getContent();

?>
<bibtip-reclist
    data-bibtip-docid="<?=$this->escapeHtml($this->driver->getPPN())?>"
    data-bibtip-gtins="<?=$this->transEsc($this->driver->getGTIN())?>"
    data-bibtip-isbns="<?=$this->escapeHtml(implode(', ', $this->driver->getISBNs()))?>"
    data-bibtip-short-title="<?=$this->escapeHtml($this->driver->getShortTitle())?>">
</bibtip-reclist>
