<?php
    // Set up page title:
    $this->headTitle($this->translate('My Profile'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Profile') . '</li>';

    // Template for use by the renderArray helper:
    $arrTemplate = '<tr><th>%%LABEL%%:</th><td> %%VALUE%%</td></tr>';
?>

<?=$this->component('show-account-menu-button')?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Your Profile')?></h2>
  <?=$this->flashmessages();?>

  <?php if ($this->auth()->getManager()->supportsPersistentLogin($this->user->getAuthMethod())): ?>
    <?php $tokens = $this->auth()->getLoginTokens($this->user->getId()); ?>
    <?php if (!$tokens): ?>
      <div class="my-profile-col"><?=$this->transEsc('No saved logins')?></div>
    <?php else: ?>
      <table class="login-tokens-table table table-responsive table-striped">
        <thead>
          <tr>
            <th scope="col" class="login_token_browser"> <?=$this->transEsc('saved_login_platform_and_browser')?></th>
            <th scope="col" class="login_token_last_login"><?=$this->transEsc('Last Login')?></th>
            <th scope="col" class="login_token_delete"><?=$this->transEsc('saved_login_actions')?></th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($tokens as $i => $token): ?>
            <tr>
              <td data-label="<?=$this->transEsc('saved_login_platform_and_browser')?>" id="login_platform_<?=$i?>"><?=$this->transEsc($token->getPlatform())?> / <?=$this->transEsc($token->getBrowser())?></td>
              <td data-label="<?=$this->transEsc('Last Login')?>" id="login_date_<?=$i?>"><?=$token->getLastLogin()->format($this->config()->dateTimeFormat())?></td>
              <td data-label="<?=$this->transEsc('saved_login_actions')?>">
                <form id="delete-login-token" method="post" action="<?=$this->url('myresearch-deletelogintoken')?>">
                  <input type="hidden" name="csrf" value="<?=$this->escapeHtmlAttr($this->auth()->getManager()->getCsrfHash())?>">
                  <input type="hidden" name="series" value="<?=$this->escapeHtmlAttr($token->getSeries())?>">
                  <input id="delete-login-token-submit" class="btn btn-danger" type="submit" name="submitButton" value="<?=$this->transEscAttr('Forget Login'); ?>" aria-labelledby="delete-login-token-submit login_platform_<?=$i?> login_date_<?=$i?>">
                </form>
              </td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
      <form id="delete-user-login-tokens" method="post" action="<?=$this->url('myresearch-deleteuserlogintokens')?>">
        <input type="hidden" name="csrf" value="<?=$this->escapeHtmlAttr($this->auth()->getManager()->getCsrfHash())?>">
        <input id="delete-user-login-tokens-submit" class="btn btn-danger" type="submit" name="submitButton" value="<?=$this->transEscAttr('Forget All')?>">
      </form>
    <?php endif; ?>
  <?php endif; ?>

  <?php if (is_array($this->profile)): ?>
    <h3><?=$this->transEsc('Library Catalog Profile')?></h3>
    <p>
      <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->user]); ?>
    </p>
    <table class="table table-striped catalog-profile">
      <?=
        $this->renderArray(
            $arrTemplate,
            $this->profile,
            [
              $this->transEsc('First Name') => 'firstname',
              $this->transEsc('Last Name') => 'lastname',
              $this->transEsc('Address') . ' 1' => 'address1',
              $this->transEsc('Address') . ' 2' => 'address2',
              $this->transEsc('Zip') => 'zip',
              $this->transEsc('City') => 'city',
              $this->transEsc('Country') => 'country',
              $this->transEsc('Phone Number') => 'phone',
              $this->transEsc('Mobile Number') => 'mobile_phone',
              $this->transEsc('Group') => 'group',
              $this->transEsc('patron_account_expires') => 'expiration_date',
            ]
        );
      ?>
    </table>
    <?php
      $proxyValues = [];
      if (!empty($this->proxiedUsers)) {
        $proxyValues['proxy_list_for'] = $this->proxiedUsers;
      }
      if (!empty($this->proxyingUsers)) {
        $proxyValues['proxy_list_by'] = $this->proxyingUsers;
      }
    ?>
    <?php if (!empty($proxyValues)): ?>
      <h3><?=$this->transEsc('proxy_list_heading')?></h3>
      <p><?=$this->transEsc('proxy_list_description')?></p>
      <?php foreach ($proxyValues as $proxyHeading => $proxyValueGroup): ?>
        <h4><?=$this->transEsc($proxyHeading)?></h4>
        <?php natsort($proxyValueGroup); ?>
        <ul>
          <?php foreach ($proxyValueGroup as $proxyValue): ?>
            <li><?=$this->escapeHtml($proxyValue)?></li>
          <?php endforeach; ?>
        </ul>
      <?php endforeach; ?>
    <?php endif; ?>
  <?php elseif ('ils-none' !== $this->ils()->getOfflineMode() && $this->patronLoginView && !empty($this->patronLoginView->getTemplate())): ?>
    <?=$this->partial($this->patronLoginView);?>
  <?php endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" role="navigation" aria-label="<?=$this->transEsc('account_menu_label')?>">
  <?=$this->accountMenu()->render('profile')?>
</div>
