<p style="margin-bottom:0">Finden Sie im Bereich PH-Bibliothek:</p>
<p style="margin-top:0; text-indent:2em">gedruckte und digitale Bücher und Zeitschriften aus dem Bestand der PH</p>

<p style="margin-bottom:0">Suchen Sie im Bereich Aufsätze und mehr:</p>
<p style="margin-top:0; text-indent:2em">Aufsätze, eBook-Kapitel und Literaturnachweise</p>

<p style="margin-bottom:0">Sichten Sie den Bestand der Universitätsbibliothek:</p>
<p style="margin-top:0; text-indent:2em">Alle Medien der UB, die die PH-Bibliothek nicht hat</p>