<div>
    <a target="_blank"
       href="https://verbundwiki.gbv.de/display/VZG/K10plus-Zentral">K10plus-Discovery</a>
    enthält ca. 321 Mio. Datensätze:<br/><br/>
</div>

<ul>
    <li>ca. 87,7 Millionen digitale Objekte und bibliographischen Nachweise aus
        den <a href="https://www.nationallizenzen.de/" class="external-link"
               rel="nofollow">Nationallizenzen</a>
    </li>
    <li>ca. 61,6 Millionen Nachweise der Bestände aller GBV-Bibliotheken (der
        GBV Gesamtkatalog <a class="external-link"
                             href="https://gso.gbv.de/DB=2.1/" rel="nofollow">GVK</a>)
    </li>
    <li>ca. 58,1 Millionen Aufsätze aus über 24000 Zeitschriften aus den Online
        Contents Daten (<a href="http://gso.gbv.de/DB=2.3/"
                           class="external-link" rel="nofollow">OLC</a>) mit
        Besitznachweisen aus der <a class="external-link"
                                    href="http://www.zeitschriftendatenbank.de/"
                                    rel="nofollow">ZDB</a>
    </li>
    <li>ca. 38,1 Millionen Nachweise des Südwestdeutschen Bibliotheksverbundes
        (<a href="http://swb.bsz-bw.de" class="external-link"
            rel="nofollow">SWB</a>)</li>
    <li>ca. 36,8 Millionen Aufsätze aus <a
                href="https://www.ncbi.nlm.nih.gov/pubmed/"
                class="external-link" rel="nofollow">PubMed / Medline</a></li>
    <li>ca. 15,3 Millionen Datensätze aus <a
                href="https://de.wikipedia.org/wiki/Fachinformationsdienste_für_die_Wissenschaft"
                class="external-link"
                rel="nofollow">Fachinformationsdiensten</a>
    </li>
    <li>ca. 13,7 Mio. Nachweise aus <a href="https://www.jstor.org"
                                       class="external-link" rel="nofollow">JSTOR</a>&nbsp
    </li>
    <li>ca. 8,6 Millionen Artikel und Zeitschriften aus dem Directory of Open
        Access Journals (<a href="http://www.doaj.org/" class="external-link"
                            rel="nofollow">DOAJ</a>) unter einer <a
                href="http://creativecommons.org/licenses/by-sa/4.0/"
                class="external-link" rel="nofollow">Creative Commons BY-SA 4.0
            Lizenz</a>&nbsp</li>
    <li>ca. 6,3 Millionen Aufsätze aus Zeitschriften des Verlages <a
                href="https://www.elsevier.com/" class="external-link"
                rel="nofollow">Elsevier</a>
    </li>
    <li>ca. 5,4 Millionen Aufsätze aus <a href="https://link.springer.com"
                                          class="external-link" rel="nofollow">Springer
            E-Journals</a></li>
    <li>ca. 4,1 Millionen Nachweise des Verbundkatalogs Öffentlicher
        Bibliotheken (<a href="https://gso.gbv.de/DB=1.126/"
                         class="external-link" rel="nofollow">ÖVK</a>)</em>
    </li>
    <li>ca. 2,4Millionen Datensätze aus <a href="https://arxiv.org/"
                                           class="external-link" rel="nofollow">arXiv</a>
    </li>
    <li>ca. 1,7 &nbsp;Millionen Aufsätze aus Zeitschriften des Verlages <a
                href="https://www.wiley.com" class="external-link"
                rel="nofollow">Wiley</a>
    </li>
    <li>ca. 942.00 &nbsp;Millionen Aufsätze aus Zeitschriften des Verlages <a
                href="https://www.degruyter.com" class="external-link"
                rel="nofollow">De Gruyter</a>
    </li>
    <li>ca. 905.000 klinische Studien aus der Datenbank <a
                href="http://ClinicalTrials.gov" class="external-link"
                rel="nofollow">ClinicalTrials.gov</a>
    </li>
    <li>ca. 317.000 Datensätze aus <a href="https://www.researchsquare.com"
                                      class="external-link" rel="nofollow">Research
            Square</a>
    </li>
    <li>ca. 271.000 Datensätze aus <a href="https://www.biorxiv.org/"
                                      class="external-link" rel="nofollow">biorXiv</a>
    </li>
    <li>ca. 52.000 Datensätze aus <a href="https://www.preprints.org/"
                                     class="external-link" rel="nofollow">preprints.org</a>
    </li>
    <li>ca. 30.000 Datensätze aus <a href="https://chemrxiv.org/"
                                     class="external-link" rel="nofollow">chemrXiv</a>
    </li>
    <li>ca. 8.400 Datensätze aus <a href="https://www.techrxiv.org"
                                    class="external-link" rel="nofollow">techrXiv</a>
    </li>
    <li>ca. 3.00 Datensätze aus <a href="https://engrxiv.org/"
                                   class="external-link"
                                   rel="nofollow">engrXiv</a>
    </li>
</ul>

<div>
    Bei technischen Fragen und Anregungen: <a
            href="javascript:window.location.href = 'mailto:' + ['boss-support','bsz-bw.de'].join('@')">boss-support@bsz-bw.de</a><br/><br/>
</div>

<div>
    Ein Projekt zum Aufbau einer gemeinsamen Infrastruktur des <a
            target="_blank" href="https://www.bsz-bw.de">Bibliotheksservice-Zentrums
        Baden-Württemberg</a> (BSZ) und der <a target="_blank"
                                               href="https://www.gbv.de/Verbundzentrale">Verbundzentrale
        des GBV</a>.<br/><br/>
</div>
