<p><b>ÖFFNUNGSZEITEN:</b></p>

<p><b>Vorlesungszeit:</b></p>
<div style="padding-bottom: 10px;">
<table>
    <tr>
        <td style="padding:0 15px 0 0">Mo - Do</td>
        <td>08:30 - 18:00 Uhr</td>
    </tr>
    <tr>
        <td style="padding:0 15px 0 0">Fr</td>
        <td>08:30 - 16:30 Uhr</td>
    </tr>
</table>
</div>
<div style="padding-bottom: 10px;">
<p><b>Vorlesungsfreie Zeit:</b></p>
<table>
    <tr>
        <td style="padding:0 15px 0 0">Mo - Fr</td>
        <td>08:30 - 16:30 Uhr</td>
    </tr>
</table>
</div>
<p>Informationen zu kurzfristigen Änderungen und Abweichungen bei den Öffnungszeiten finden Sie auf unserer <a href="https://www.ph-gmuend.de/hochschule/bibliothek" target="_blank">Website</a>.</p>

