<p><b>ÖFFNUNGSZEITEN: Montag - Freitag 9:00 - 18:00 Uhr</b></p>

<p><b>Änderungen:</b></p>
<p>24.2.25 - 11.4.25 Mo - Fr 9:00 - 16:30 Uhr</p>
<p>14.4.25 - 8.8.25 Mo - Fr 9:00 - 18:00 Uhr</p>

<p>(Ausnahme Exkursionswoche 10.6. - 13.6.25 Di - Fr 9:00 - 16:30 Uhr)</p>

<p>11.8.25 - 29.8.25 Mo - Fr 9:00 - 14:00 Uhr</p>
<p>1.9.25 - 10.10.25 Mo - Fr 9:00 - 16:30 Uhr</p>
<p>ab 13.10.25 Mo - Fr 9:00 - 18:00 Uhr</p>

<p>Details dazu, welche Medien weiterhin vorbestellt werden müssen, finden Sie auf der <a href="https://bibliothek.ph-gmuend.de/" target="_blank">Website der Bibliothek</a>.</p>

