<p><b>Opening hours:</b></p>

<p><b>During lecture period:</b></p>
<div style="padding-bottom: 10px;">
    <table>
        <tr>
            <td style="padding:0 15px 0 0">Mon–Thu</td>
            <td>8.30 am – 6.00 pm</td>
        </tr>
        <tr>
            <td style="padding:0 15px 0 0">Fri</td>
            <td>8.30 am – 4.30 pm</td>
        </tr>
    </table>
</div>
<div style="padding-bottom: 10px;">
    <p><b>Outside lecture period:</b></p>
    <table>
        <tr>
            <td style="padding:0 15px 0 0">Mon–Fri</td>
            <td>8.30 am – 4.30 pm</td>
        </tr>
    </table>
</div>

Information about short-term changes and deviations to the opening hours can be found on our <a href="https://www.ph-gmuend.de/hochschule/bibliothek" target="_blank">website</a>.