<div>
    <?php foreach ($this->data as $current): ?>
        <?php if (is_array($current['label'])): ?>
            <a class="external localUrls"
               href="<?= $current['url'] ?>"><?= $this->transEsc($current['label'][0]) ?></a>
            <?php if ($this->client()->is('local_url_help_regex') && isset($current['label'][1])): ?>
                <?php $htmllink = preg_replace(
                    $this->client()->getHelpRegEx(),
                    "<a class='external' href='" . $this->client()->getHelpUrl() . "'>" . $this->client()->getHelpGroups() . "</a>",
                    $this->transEsc($current['label'][1])
                ) ?>
                <?= $htmllink ?>
            <?php elseif (isset($current['label'][1])): ?>
                &ndash; <?= $this->transEsc($current['label'][1]) ?>
                <br/>
            <?php endif; ?>
        <?php else: ?>
            <a class="external"
               href="<?= $current['url'] ?>"><?= $this->transEsc($current['label']) ?></a>
        <?php endif ?>
    <?php endforeach; ?>
</div>