<?php $hf = $this->searchMemory()->getHiddenFilterString($this->searchClassId); ?>
<?php foreach($this->data as $field): ?>
    <?php if (is_array($field)): ?>
        <a href="<?=$this->url('record', ['id' => $field['ppn']])?>"><?=$this->escapeHtml($field['title'])?></a>
    <?php else: ?>
        <a href="<?=$this->url('search-results')?>?lookfor=%22<?=urlencode($field)?>%22&amp;type=AllFields&amp;filter[]=~material_content_type:%22Journal/Magazine%22<?= $hf ?>"><?=$this->escapeHtml($field)?></a><br/>
    <?php endif; ?>
<?php endforeach; ?>