<h2>Rechercheportal der Hochschule Mainz</h2>
<ul>
    <li>
        <strong>Bibliothekskatalog</strong> Hier finden Sie den Medienbestand der Hochschule Mainz, darunter Bücher, Zeitschriften, elektronische Ressourcen und weitere Medien.
    </li>
    <li>
        <strong>HSMeta</strong> In diesem Bereich können Sie nach online verfügbaren Aufsätzen und Büchern sowie nach Literaturhinweisen aus verschiedenen Datenbanken suchen. Dabei werden auch Quellen angezeigt, die nicht zum Bestand der Hochschule Mainz gehören.
    </li>
    <li>
        <strong>Freier Online-Zugriff</strong> Hier werden frei zugängliche Open-Access-Publikationen wie Aufsätze, Bücher und weitere Literaturhinweise aufgeführt. Diese Inhalte können auch außerhalb des Hochschulnetzes genutzt werden.
    </li>
</ul>
<p>Bitte beachten Sie, dass über das Rechercheportal nicht sämtliche Datenbanken der Hochschule Mainz durchsucht werden. Für eine gezielte und fachlich detaillierte Recherche empfiehlt es sich daher, zusätzlich direkt in einer passenden Fachdatenbank zu suchen. Eine Übersicht finden Sie hier: <a href="https://www.hs-mainz.de/studium/services/fachbereichsuebergreifend/bibliothek/datenbanken/" target="_blank" class="external">Datenbanken</a>.</p>
