<h2>Mainz University of Applied Sciences Research Portal</h2>
<ul>
    <li>
        <strong>Library Catalog</strong> Here you will find the Mainz University of Applied Sciences collection, including books, journals, electronic resources, and other media.
    </li>
    <li>
        <strong>HSMeta</strong> In this section, you can search for articles and books available online, as well as bibliographic references from various databases. Sources that are not part of the Mainz University of Applied Sciences collection are also displayed.
    </li>
    <li>
        <strong>Free Online Access</strong> This section lists freely accessible open-access publications such as articles, books, and other bibliographic references. This content can also be accessed outside the university network.
    </li>
</ul>
<p>Please note that not all of Mainz University of Applied Sciences’ databases are searchable via the search portal. For a targeted and subject-specific search, it is therefore recommended to also search directly in a relevant subject-specific database. You can find an overview here: <a href="https://www.hs-mainz.de/studium/services/fachbereichsuebergreifend/bibliothek/datenbanken/" target="_blank" class="external">Databases</a>.</p>
